# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/profile-picture.jpeg"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

 # giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = true
    repo = "jordyvanvorselen/blog"
    repoId = "600214808"
    category = "General"
    categoryId = "40347743"
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true